# from: https://github.com/clap-rs/clap/blob/master/.github/workflows/coverage.yml
name: Coverage
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
concurrency:
  group: coverage-${{ github.ref }}
  cancel-in-progress: true
jobs:
  coverage:
    name: Coverage
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: llvm-tools-preview
          override: true

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install llvm-cov
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-llvm-cov
          version: 0.1.0-alpha.4
          use-tool-cache: true

      - name: Build Plugins
        run: ${{matrix.ENV_VARS}} cargo build --all

      - name: Coverage
        uses: actions-rs/cargo@v1
        with:
          command: llvm-cov
          args: --all-features --workspace --lcov --output-path lcov.info

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: lcov.info
          github-token: ${{ secrets.github_token }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: lcov.info
          fail_ci_if_error: true
